import test from 'node:test';
import assert from 'node:assert/strict';
import {resolvedHeaders,calculatedLines,documentColumns,documentHTML,priceExplanation} from '../src/documents.js';
const order={folio:'PO-12',fecha:'2026-09-05',moneda_compra:'USD',moneda_venta:'USD',partidas:[{codigo:'P1',cantidad:'200',unidad:'ROLL',descripcion_compra:'Descripción de Purchase Order',descripcion_venta:'Otra descripción',precio_compra:'78',precio_venta:'80',peso_unitario_kg:'65'}],encabezados:{purchase_order:{referencia_proveedor:'SUP-7'},invoice:{folio:'INV-31'},orden_compra_mexico:{folio:'MX-20'}}};
test('invoice references and packing folio/date/PO are derived from their source documents',()=>{const h=resolvedHeaders(order);assert.equal(h.invoice.referencia_cliente,'PO-12');assert.equal(h.invoice.referencia_proveedor,'SUP-7');assert.equal(h.packing_list.folio,'INV-31PL');assert.equal(h.packing_list.invoice_num,'INV-31');assert.equal(h.packing_list.referencia_cliente,'MX-20');assert.equal(h.packing_list.fecha,h.invoice.fecha);});
test('each document uses the columns and description linked in the Excel',()=>{assert.deepEqual(documentColumns.invoice.map(x=>x[0]),['cantidad','unidad','codigo','descripcion_compra','precio_venta','importe_venta']);assert.ok(!documentColumns.packing_list.some(([k])=>k.includes('precio')));const lines=calculatedLines(order.partidas);assert.equal(lines[0].importe_compra,'15600.00');assert.equal(lines[0].importe_venta,'16000.00');assert.equal(lines[0].peso_total_kg,'13000.000000');});
test('missing prices stay unknown rather than displaying a false zero total',()=>{const o=structuredClone(order);o.partidas[0].precio_venta=null;assert.equal(calculatedLines(o.partidas)[0].importe_venta,null);assert.match(documentHTML(o,'invoice',{empresas:[],domicilios_empresa:[]}),/Incomplete: missing data/);});
test('a changed quantity updates invoice, Mexican PO and packing totals together',()=>{const o=structuredClone(order);o.partidas[0].cantidad='100';const c={empresas:[],domicilios_empresa:[]};for(const kind of ['invoice','orden_compra_mexico'])assert.match(documentHTML(o,kind,c),/8000.00/);assert.match(documentHTML(o,'packing_list',c),/6500.000/);assert.equal(order.partidas[0].cantidad,'200');});
test('missing selected company price explains other sources without substituting them',()=>{const p=[{producto_id:'p',unidad_id:'u',moneda:'USD',cliente_id:'other',vigente_desde:'2026-09-05'}];assert.match(priceExplanation(p,{producto_id:'p',unidad_id:'u',moneda:'USD',cliente_id:'selected'},'2026-09-05',[{id:'other',razon_social:'Cliente con precio'}]),/Cliente con precio/);});
