import {createClient} from '@supabase/supabase-js';
import {escapeHTML as e,kinds,total,currentPrice,orderFromRevision} from './domain.js';
import './style.css';
const db=createClient('https://qfwvlhzvgbqmcajdmczj.supabase.co','sb_publishable_j7NC2Zo47BrPQC2SfdGYuA_k3XSqQVX');
const app=document.querySelector('#app'),dialog=document.querySelector('#editor');
const tables=['empresas','roles_empresa','domicilios_empresa','unidades','productos','precios_compra','precios_venta'];
let catalogs={},orders=[],order=null,view='orders',selectedKind='purchase_order',dirty=false,session=null;
const today=()=>new Date().toLocaleDateString('en-CA');
function notify(s){document.querySelector('#notice').textContent=s;}
async function run(fn){try{await fn();}catch(x){notify(x.message||String(x));}}
async function query(q){const {data,error}=await q;if(error)throw error;return data;}
async function all(table){let result=[];for(let page=0;;page++){const rows=await query(db.from(table).select('*').range(page*1000,page*1000+999));result.push(...rows);if(rows.length<1000)return result;}}
function label(t,id){const row=(catalogs[t]||[]).find(x=>x.id===id);return row?row.razon_social||[row.codigo,row.descripcion_compra||row.nombre||row.direccion].filter(Boolean).join(' · '):id||'';}
function opts(rows,value,empty=true){return (empty?'<option value="">Seleccionar…</option>':'')+rows.map(r=>`<option value="${e(r.id)}" ${r.id===value?'selected':''}>${e(r.razon_social||r.codigo||r.nombre)}</option>`).join('');}
function byRole(role){const ids=new Set(catalogs.roles_empresa.filter(r=>r.rol===role).map(r=>r.empresa_id));return catalogs.empresas.filter(c=>ids.has(c.id)&&c.activa&&(role!=='proveedor'||c.pais==='CN'));}
function field(name,title,value='',type='text',extra=''){return `<label>${e(title)}<input name="${e(name)}" type="${type}" value="${e(value)}" ${extra}></label>`;}
function shell(content){app.innerHTML=`<aside><a class="brand" href="#">PHASA<span>ORDERS</span></a><p>Operaciones de importación</p><nav><button data-nav="orders" class="${view==='orders'?'selected':''}">Órdenes e historial</button><button data-nav="catalogs" class="${view==='catalogs'?'selected':''}">Catálogos</button></nav><small>Tu información se guarda<br>con historial de versiones.</small><button id="logout" class="quiet">Cerrar sesión</button></aside><main>${content}</main>`;document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>run(async()=>{if(dirty&&!confirm('Hay cambios sin guardar. ¿Quieres descartarlos?'))return;dirty=false;view=b.dataset.nav;order=null;render();}));document.querySelector('#logout').onclick=()=>run(async()=>{if(dirty&&!confirm('Hay cambios sin guardar. ¿Salir?'))return;await db.auth.signOut();});}
async function refresh(){const data=await Promise.all(tables.map(all));tables.forEach((t,i)=>catalogs[t]=data[i]);orders=await query(db.from('purchase_orders').select('*').order('updated_at',{ascending:false}));}
function login(){app.innerHTML=`<div class="login"><div class="intro"><span class="eyebrow">PHASA / OPERACIONES</span><h1>De una orden<br>a todo el flujo.</h1><p>Productos, documentos e historial.<br>En un solo lugar.</p></div><form id="login"><span class="badge">Acceso privado</span><h2>Bienvenida</h2><p>Recibe un enlace de acceso en tu correo autorizado.</p>${field('email','Correo electrónico','','email','required autocomplete="email"')}<button>Enviar enlace de acceso</button><small>Solo el correo autorizado puede consultar la información.</small></form></div>`;document.querySelector('#login').onsubmit=ev=>{ev.preventDefault();run(async()=>{const b=ev.target.querySelector('button');b.disabled=true;try{const {error}=await db.auth.signInWithOtp({email:new FormData(ev.target).get('email'),options:{emailRedirectTo:location.origin}});if(error)throw error;notify('Revisa tu correo y abre el enlace para entrar.');}finally{b.disabled=false;}});};}
function newOrder(){order={folio:'',fecha:today(),empresa_usa_id:byRole('empresa_usa')[0]?.id,proveedor_id:'',cliente_id:'',domicilio_entrega_id:'',moneda_compra:'USD',moneda_venta:'USD',partidas:[],encabezados:{}};selectedKind='purchase_order';dirty=false;render();}
function render(){if(order)return renderOrder();if(view==='catalogs')return renderCatalogs();shell(`<header><div><span class="eyebrow">OPERACIONES</span><h1>Órdenes e historial</h1><p>Consulta cada operación y las versiones de sus documentos.</p></div><button id="new">＋ Nueva Purchase Order</button></header><div class="metrics"><article><span>Órdenes guardadas</span><strong>${orders.length}</strong></article><article><span>Productos en catálogo</span><strong>${catalogs.productos.length}</strong></article><article><span>Clientes</span><strong>${byRole('cliente_mexico').length}</strong></article></div><section><input id="searchOrders" placeholder="Buscar por folio, cliente o proveedor" aria-label="Buscar órdenes"><div id="orderList"></div></section>`);document.querySelector('#new').onclick=newOrder;document.querySelector('#searchOrders').oninput=orderList;orderList();}
function orderList(){const search=document.querySelector('#searchOrders').value.toLowerCase();const rows=orders.filter(o=>[o.folio,label('empresas',o.cliente_id),label('empresas',o.proveedor_id)].join(' ').toLowerCase().includes(search));document.querySelector('#orderList').innerHTML=rows.length?`<table><thead><tr><th>Purchase Order</th><th>Cliente</th><th>Fecha</th><th>Versión</th><th></th></tr></thead><tbody>${rows.map(o=>`<tr><td><b>${e(o.folio)}</b><small>${e(label('empresas',o.proveedor_id))}</small></td><td>${e(label('empresas',o.cliente_id))}</td><td>${e(o.fecha)}</td><td>v${o.revision}</td><td><button class="quiet" data-open="${o.id}">Abrir historial</button></td></tr>`).join('')}</tbody></table>`:'<div class="empty"><h2>Aquí comienza el historial</h2><p>Crea una Purchase Order para guardar la operación y sus documentos.</p></div>';document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>run(()=>openHistory(b.dataset.open)));}
async function openHistory(id){const revisions=await query(db.from('revisiones_operacion').select('*').eq('purchase_order_id',id).order('numero_revision',{ascending:false}));const latest=orders.find(o=>o.id===id);dialog.innerHTML=`<h2>${e(latest.folio)}</h2><p>Cada versión conserva los datos que tenía al guardarse.</p>${revisions.map(r=>`<article class="revision"><div><b>Versión ${r.numero_revision}</b><small>${e(new Date(r.created_at).toLocaleString('es-MX'))} · ${e(r.motivo||'Guardado de operación')}</small></div><button data-rev="${r.id}">Abrir versión</button></article>`).join('')}<button id="closeDialog" class="quiet">Cerrar</button>`;dialog.showModal();document.querySelector('#closeDialog').onclick=()=>dialog.close();dialog.querySelectorAll('[data-rev]').forEach(b=>b.onclick=()=>{order=orderFromRevision(revisions.find(r=>r.id===b.dataset.rev),latest.revision);dirty=false;dialog.close();renderOrder();notify('Puedes editar esta versión. Al guardar se creará una nueva para los cuatro documentos.');});}
const headerFields=[['folio','Folio del documento'],['fecha','Fecha del documento','date'],['condiciones_pago','Condiciones de pago'],['incoterm','Incoterm y lugar'],['via_transporte','Vía de transporte'],['puerto_entrada','Puerto de entrada'],['referencia_cliente','Referencia del cliente'],['referencia_proveedor','Referencia del proveedor'],['observaciones','Observaciones']];
function renderOrder(){shell(`<header><div><span class="eyebrow">CAPTURA DE OPERACIÓN</span><h1>${e(order.folio||'Nueva Purchase Order')}</h1><p>Los cambios compartidos actualizan los cuatro documentos y conservan el historial.</p></div><button id="save">Guardar nueva versión</button></header><form id="orderForm"><section><h2>1. Proveedor y destino</h2><div class="grid">${field('folio','Folio de Purchase Order',order.folio,'text','required')}${field('fecha','Fecha',order.fecha,'date','required')}<label>Proveedor chino<select name="proveedor_id" required>${opts(byRole('proveedor'),order.proveedor_id)}</select></label><label>Ship To · Cliente mexicano<select name="cliente_id" required>${opts(byRole('cliente_mexico'),order.cliente_id)}</select></label>${field('moneda_compra','Moneda de compra',order.moneda_compra,'text','required pattern="[A-Z]{3}"')}${field('moneda_venta','Moneda de venta',order.moneda_venta,'text','required pattern="[A-Z]{3}"')}</div><p id="address" class="hint"></p></section><section><h2>2. Productos</h2><p>Busca por código o nombre. Los precios se toman del proveedor y cliente seleccionados.</p><input id="productSearch" placeholder="Buscar código o nombre del producto" aria-label="Buscar producto" autocomplete="off"><div id="productResults"></div><div class="table-scroll" id="lines"></div><div id="totals" class="totals"></div></section><section><h2>3. Documentos</h2><div class="tabs">${Object.entries(kinds).map(([k,v])=>`<button type="button" data-kind="${k}" class="${k===selectedKind?'selected':''}">${v}</button>`).join('')}</div><p>Estos campos pertenecen al documento seleccionado. Las cantidades y precios se editan arriba.</p><div class="grid" id="headers"></div></section><section>${field('motivo','Motivo del cambio (opcional)',order.motivo||'')}<p class="hint">Folios, condiciones comerciales y redondeo se están validando. Esta etapa guarda borradores; la exportación con las plantillas originales se incorporará después de verificar sus formatos.</p></section></form>`);
const form=document.querySelector('#orderForm');form.onchange=ev=>{if(ev.target.closest('#headers')||ev.target.closest('#lines'))return;const k=ev.target.name;if(k){const old=order[k];if(['proveedor_id','cliente_id','moneda_compra','moneda_venta','fecha'].includes(k)&&order.partidas.length){notify('Con productos capturados, crea otra orden para cambiar proveedor, cliente, fecha o moneda y volver a obtener sus precios.');ev.target.value=old;return;}order[k]=ev.target.value;dirty=true;if(k==='cliente_id'){order.domicilio_entrega_id=catalogs.domicilios_empresa.find(a=>a.empresa_id===order.cliente_id&&a.activo&&a.es_domicilio_entrega)?.id||'';showAddress();}}};
document.querySelector('#save').onclick=()=>run(saveOrder);document.querySelector('#productSearch').oninput=searchProducts;document.querySelectorAll('[data-kind]').forEach(b=>b.onclick=()=>{selectedKind=b.dataset.kind;document.querySelectorAll('[data-kind]').forEach(x=>x.classList.toggle('selected',x===b));showHeaders();});showAddress();showLines();showHeaders();}
function showAddress(){const a=catalogs.domicilios_empresa.find(x=>x.id===order.domicilio_entrega_id);document.querySelector('#address').textContent=a?`Entrega: ${a.direccion}, ${a.ciudad||''}`:'Selecciona un cliente con domicilio de entrega en su catálogo.';}
function searchProducts(){const text=document.querySelector('#productSearch').value.toLowerCase().trim();const results=text?catalogs.productos.filter(p=>p.activo&&[p.codigo,p.descripcion_compra,p.descripcion_venta,p.descripcion_mexico].join(' ').toLowerCase().includes(text)).slice(0,15):[];document.querySelector('#productResults').innerHTML=results.map(p=>`<button type="button" data-product="${p.id}"><b>${e(p.codigo)}</b> ${e(p.descripcion_compra)}</button>`).join('');document.querySelectorAll('[data-product]').forEach(b=>b.onclick=()=>addProduct(b.dataset.product));}
function addProduct(id){if(!order.proveedor_id||!order.cliente_id){notify('Primero selecciona proveedor y cliente.');return;}const p=catalogs.productos.find(x=>x.id===id);if(p.unidad_compra_id!==p.unidad_venta_id){notify('Este producto tiene unidades de compra y venta distintas. Hace falta definir su conversión antes de usarlo.');return;}const buy=currentPrice(catalogs.precios_compra,{proveedor_id:order.proveedor_id,producto_id:id,unidad_id:p.unidad_compra_id,moneda:order.moneda_compra},order.fecha);const sell=currentPrice(catalogs.precios_venta,{vendedor_id:order.empresa_usa_id,cliente_id:order.cliente_id,producto_id:id,unidad_id:p.unidad_venta_id,moneda:order.moneda_venta},order.fecha);order.partidas.push({producto_id:id,codigo:p.codigo,descripcion_compra:p.descripcion_compra,descripcion_venta:p.descripcion_venta||p.descripcion_compra,descripcion_mexico:p.descripcion_mexico||p.descripcion_compra,unidad:catalogs.unidades.find(u=>u.id===p.unidad_compra_id)?.codigo||'',cantidad:'1',precio_compra:buy?.precio??null,precio_venta:sell?.precio??null,peso_unitario_kg:p.peso_unitario_kg});dirty=true;document.querySelector('#productSearch').value='';document.querySelector('#productResults').innerHTML='';showLines();}
function showLines(){document.querySelector('#lines').innerHTML=order.partidas.length?`<table><thead><tr><th>Producto</th><th>Cantidad</th><th>Unidad</th><th>Compra / unidad</th><th>Venta / unidad</th><th>Kg / unidad</th><th></th></tr></thead><tbody>${order.partidas.map((l,i)=>`<tr><td><b>${e(l.codigo)}</b><small>${e(l.descripcion_compra)}</small></td>${['cantidad','unidad','precio_compra','precio_venta','peso_unitario_kg'].map(k=>`<td><input aria-label="${k} de ${e(l.codigo)}" data-i="${i}" data-key="${k}" type="${k==='unidad'?'text':'number'}" ${k==='unidad'?'readonly':'step="any" min="0"'} value="${e(l[k])}" placeholder="Falta dato"></td>`).join('')}<td><button type="button" data-remove="${i}" class="quiet" aria-label="Quitar ${e(l.codigo)}">×</button></td></tr>`).join('')}</tbody></table>`:'<p class="hint">Agrega el primer producto para comenzar.</p>';document.querySelectorAll('[data-key]').forEach(input=>input.onchange=()=>{order.partidas[Number(input.dataset.i)][input.dataset.key]=input.value===''?null:input.value;dirty=true;showTotals();});document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{order.partidas.splice(Number(b.dataset.remove),1);dirty=true;showLines();});showTotals();}
function showTotals(){document.querySelector('#totals').innerHTML=`<span>Compra <b>${e(order.moneda_compra)} ${total(order.partidas,'precio_compra')}</b></span><span>Venta <b>${e(order.moneda_venta)} ${total(order.partidas,'precio_venta')}</b></span><span>Peso <b>${total(order.partidas,'peso_unitario_kg')} kg</b></span>`;}
function showHeaders(){const values=order.encabezados[selectedKind]||{};document.querySelector('#headers').innerHTML=headerFields.map(([k,t,type])=>field(k,t,values[k]||'',type||'text')).join('');document.querySelectorAll('#headers input').forEach(input=>input.onchange=()=>{order.encabezados[selectedKind]??={};order.encabezados[selectedKind][input.name]=input.value;dirty=true;});}
async function saveOrder(){if(!document.querySelector('#orderForm').reportValidity())return;if(!order.domicilio_entrega_id)throw Error('Completa el domicilio de entrega del cliente.');if(!order.partidas.length)throw Error('Agrega al menos un producto.');const b=document.querySelector('#save');b.disabled=true;try{order.clave_guardado??=crypto.randomUUID();const result=await query(db.rpc('guardar_operacion',{p:order}));order.id=result.id;order.revision=result.revision;order.revision_origen_id=result.revision_id;delete order.clave_guardado;dirty=false;await refresh();renderOrder();notify(`Versión ${result.revision} guardada con sus cuatro documentos.`);}finally{b.disabled=false;}}
const names={empresas:'Empresas',roles_empresa:'Funciones de empresas',domicilios_empresa:'Domicilios',unidades:'Unidades',productos:'Productos',precios_compra:'Precios de compra',precios_venta:'Precios de venta'};
let catalogTable='productos';
const definitions={
 empresas:[['codigo_interno','Código interno'],['razon_social','Razón social'],['pais','País (CN, MX, US, ES)'],['identificacion_fiscal','Identificación fiscal'],['telefono','Teléfono'],['email','Correo'],['activa','Activa','boolean']],
 roles_empresa:[['empresa_id','Empresa','empresas'],['rol','Función','role'],['codigo_catalogo_origen','Código en catálogo de origen']],
 domicilios_empresa:[['empresa_id','Empresa','empresas'],['direccion','Calle y número'],['ciudad','Ciudad'],['estado','Estado'],['codigo_postal','Código postal'],['pais','País (CN, MX, US, ES)'],['es_domicilio_entrega','Domicilio de entrega','boolean'],['activo','Activo','boolean']],
 unidades:[['codigo','Código'],['nombre','Nombre'],['etiqueta_es','Etiqueta en español'],['etiqueta_en','Etiqueta en inglés'],['permite_fraccion','Permite fracciones','boolean'],['activa','Activa','boolean']],
 productos:[['codigo','Código'],['descripcion_compra','Descripción de compra'],['descripcion_venta','Descripción de venta'],['descripcion_mexico','Descripción en México'],['unidad_compra_id','Unidad de compra','unidades'],['unidad_venta_id','Unidad de venta','unidades'],['unidad_mexico_id','Unidad en México','unidades'],['peso_unitario_kg','Peso por unidad de compra (kg)','number'],['factor_conversion','Factor de conversión','number'],['activo','Activo','boolean']],
 precios_compra:[['proveedor_id','Proveedor','empresas'],['producto_id','Producto','productos'],['unidad_id','Unidad','unidades'],['moneda','Moneda (USD, MXN)'],['precio','Precio por unidad','number'],['vigente_desde','Vigente desde (incluido)','date'],['vigente_hasta','Vigente hasta (excluido)','date']],
 precios_venta:[['vendedor_id','Empresa estadounidense','empresas'],['cliente_id','Cliente mexicano','empresas'],['producto_id','Producto','productos'],['unidad_id','Unidad','unidades'],['moneda','Moneda (USD, MXN)'],['precio','Precio por unidad','number'],['vigente_desde','Vigente desde (incluido)','date'],['vigente_hasta','Vigente hasta (excluido)','date']]
};
function renderCatalogs(){shell(`<header><div><span class="eyebrow">INFORMACIÓN DEL NEGOCIO</span><h1>Catálogos</h1><p>Agrega y actualiza los datos que alimentan tus órdenes.</p></div><button id="addCatalog">＋ Agregar registro</button></header><section><p>Para una empresa nueva: agrega sus datos, asigna su función y registra su domicilio. Después puedes asignarle precios por producto.</p><div class="tabs">${tables.map(t=>`<button data-table="${t}" class="${catalogTable===t?'selected':''}">${names[t]}</button>`).join('')}</div><input id="catalogSearch" placeholder="Buscar en este catálogo" aria-label="Buscar en catálogo"><div class="table-scroll" id="catalogRows"></div></section>`);document.querySelectorAll('[data-table]').forEach(b=>b.onclick=()=>{catalogTable=b.dataset.table;renderCatalogs();});document.querySelector('#addCatalog').onclick=()=>editCatalog({});document.querySelector('#catalogSearch').oninput=catalogRows;catalogRows();}
function catalogRows(){const search=document.querySelector('#catalogSearch').value.toLowerCase();const cols=definitions[catalogTable];const rows=catalogs[catalogTable].map((r,i)=>({r,i})).filter(({r})=>cols.map(([k,,type])=>tables.includes(type)?label(type,r[k]):r[k]).join(' ').toLowerCase().includes(search));document.querySelector('#catalogRows').innerHTML=`<table><thead><tr>${cols.slice(0,5).map(([,t])=>`<th>${e(t)}</th>`).join('')}<th></th></tr></thead><tbody>${rows.slice(0,150).map(({r,i})=>`<tr>${cols.slice(0,5).map(([k,,type])=>`<td>${e(tables.includes(type)?label(type,r[k]):typeof r[k]==='boolean'?(r[k]?'Sí':'No'):r[k])}</td>`).join('')}<td><button class="quiet" data-edit="${i}">Editar</button></td></tr>`).join('')}</tbody></table><p>${rows.length>150?'Se muestran 150 coincidencias. Escribe una búsqueda más específica.':`${rows.length} registros`}</p>`;document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>editCatalog(catalogs[catalogTable][Number(b.dataset.edit)]));}
function editCatalog(row){const cols=definitions[catalogTable];dialog.innerHTML=`<form id="catalogForm"><h2>${row.id||row.empresa_id?'Editar':'Agregar'} · ${names[catalogTable]}</h2><div class="grid">${cols.map(([k,t,type])=>type==='boolean'?`<label class="check"><input name="${k}" type="checkbox" ${(row[k]??['activo','activa'].includes(k))?'checked':''}>${e(t)}</label>`:tables.includes(type)?`<label>${e(t)}<select name="${k}">${opts(catalogs[type].map(r=>({...r,razon_social:label(type,r.id)})),row[k])}</select></label>`:type==='role'?`<label>Función<select name="rol">${[['proveedor','Proveedor'],['cliente_mexico','Cliente mexicano'],['empresa_usa','Empresa estadounidense']].map(([v,t])=>`<option value="${v}" ${row.rol===v?'selected':''}>${t}</option>`).join('')}</select></label>`:field(k,t,row[k]??'',type||'text',type==='number'?'step="any" min="0"':'')).join('')}</div><div class="actions"><button>Guardar</button><button type="button" id="cancel" class="quiet">Cancelar</button></div><p id="catalogError" role="alert"></p></form>`;dialog.showModal();document.querySelector('#cancel').onclick=()=>dialog.close();document.querySelector('#catalogForm').onsubmit=async ev=>{ev.preventDefault();const btn=ev.target.querySelector('button');btn.disabled=true;try{const f=new FormData(ev.target);const values=Object.fromEntries(cols.map(([k,,type])=>[k,type==='boolean'?f.has(k):(f.get(k)||null)]));let q;if(row.id)q=db.from(catalogTable).update(values).eq('id',row.id);else if(catalogTable==='roles_empresa'&&row.empresa_id)q=db.from(catalogTable).update(values).eq('empresa_id',row.empresa_id).eq('rol',row.rol);else q=db.from(catalogTable).insert(values);await query(q.select());await refresh();dialog.close();renderCatalogs();notify('Catálogo actualizado. Las versiones guardadas conservan sus datos anteriores.');}catch(x){document.querySelector('#catalogError').textContent=x.message;}finally{btn.disabled=false;}};}
async function loadSession(s){session=s;if(!s){catalogs={};orders=[];order=null;dirty=false;login();return;}const allowed=await query(db.rpc('acceso_permitido'));if(!allowed){await db.auth.signOut();notify('Este correo no tiene acceso al sistema.');return;}await refresh();render();}
db.auth.onAuthStateChange((event,s)=>{if(event==='SIGNED_OUT'||event==='SIGNED_IN'&&session?.user.id!==s?.user.id)setTimeout(()=>run(()=>loadSession(s)),0);});
window.addEventListener('beforeunload',ev=>{if(dirty){ev.preventDefault();ev.returnValue='';}});
run(async()=>{const {data:{session:s},error}=await db.auth.getSession();if(error)throw error;await loadSession(s);});
